<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To Do List</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="logInStyle.css">
</head>
<body>
  <div class="container">
    <div class="header-box">
      <h1>My To Do List</h1>
      <h2>Get things done, one task at a time.</h2>
    </div>

    <!-- Sign Up button (hidde or show)-->
    <input type="checkbox" id="showForm" hidden>
    <label for="showForm" class="btn">Start now!</label>

    <!-- Form -->
    <div class="form-container">
      <form id="signup-form" method="POST">
        <input type="email" name="email" placeholder="E-mail" required>
        <button type="submit" class="btn">LOG IN</button>
        <a href="taskList.phtml">Sign In</a>
      </form>
      <p class="signin-link">Or <a href="signUp.phtml">Sign Up</a></p>
    </div>
  </div>
</body>
</html>
